---
title: "HW5"
author: "Nick Kim"
format: html
---

Link to my [github]("www.github.com/nick-kimm/STAT-506") repository 

## Problem 1

Creating a class to represent rational numbers

#part a:

Setting constructor and Validity 
```{r}
#' Rational class
#' 
#'Defining a class object that'll take in two integer inputs, one for the numerator and one for the denominator. This will be used to return a rational number given the input.
#'
#'
#' @return rational number
#' 
setClass("rational",
          slots = c(numerator = "numeric",
                    denominator = "numeric")
)

rational <- function(n, d) {
  if (d == 0) {
    stop("Denominator cannot be zero.")
  }
  new("rational", numerator = n, denominator = d)
}

setValidity("rational",
            function(object){
              if (object@denominator == 0){
                return("Denominator can't be zero")
              }
              return(TRUE)
            })
```

Show method
```{r}
setMethod("show","rational",
          function(object) {
            cat("Numerator :")
            str(object@numerator)
            cat("\n")
            cat("Denominator :")
            str(object@denominator)
            cat("\n")
            return(invisible(object))
})
```

Simplify method
```{r}
#' Greatest Common Divisor
#'
#'Will find the greatest common divisor for the given numerator and denominator values in the "rational" object. The function will use the Euclidean method, which is a recursive solution to get the gcd. This algorithm will continiously take the mod of the numbers until the remainder is zero, where a will store the value of previous operation. 
#'
#' @param a,b 
#'
#' @return integer of the gcd
#' 
gcd<-function(a,b){
  if (b == 0){
    return(abs(a))
  }else{
    return(gcd(b,a%%b))
    }
}

#' Simplify
#'Will reduce the rational down to its simplified form. This will be found by dividing the numerator by the gcd of the numerator and denominator and similarly for the denominator.
#' @param object 
#'
#' @return simplified rational of the input
#' 
setGeneric("simplify",
           function(object){
             n<-object@numerator/gcd(object@numerator,object@denominator)
             d<-object@denominator/gcd(object@numerator,object@denominator)
             return(paste(n,"/",d, sep=""))
           }
)
```

```{r}
#' Quotient
#' Will return the quotient of the rational number to a specified digit place. The default digit length will be set at 6.
#'
#' @param object 
#' @param digits 
#'
#' @return Quotient of rational to a specified digit place
#' 
setGeneric("quotient",
           function(object, digits=6){
             if (is.numeric(digits)==FALSE){
               return("Digit is not a numeric value")
             }else{
               q<-object@numerator/object@denominator
               return(print(q,digits=digits))
            }
           })
```

```{r}
#' Rational Addition
#' Will make sure the input are both in the rational class and then return the added value of the two. This will be done by calling a new rational where the numerator is the added value of the numerators and the denominator is found in the same fashion.
#'
#' @param e1 rational. 
#' @param e2 rational. 
#'
#' @return Added value of the two  rational numbers
setMethod("+", signature(e1 = "rational",
                         e2 = "rational"),
          function(e1,e2){
            newnum <- rational(e1@numerator + e2@numerator, e1@denominator + e2@denominator)
            return(paste(newnum@numerator,"/",newnum@denominator,sep=""))
          })

#'Rational Subtraction 
#'Will make sure the input are both in the rational class and then return the subtracted value of the two. This will be done by calling a new rational where the numerator is the subtracted value of the numerators and the denominator is found in the same fashion.
#'
#' @param e1 rational. 
#' @param e2 rational. 
#'
#' @return Subtracted value of the two rational numbers
setMethod("-", signature(e1 = "rational",
                         e2 = "rational"),
          function(e1,e2){
            newnum <- rational(e1@numerator - e2@numerator, e1@denominator - e2@denominator)
            return(paste(newnum@numerator,"/",newnum@denominator,sep=""))
          })

#' Rational Multiplication
#' Will make sure the input are both in the rational class and then return the multiplied value of the two. This will be done by calling a new rational where the numerator is the multiplied value of the numerators and the denominator is found in the same fashion.
#'
#' @param e1 rational. 
#' @param e2 rational. 
#'
#' @return Multiplied rational of two rationals
setMethod("*", signature(e1 = "rational",
                         e2 = "rational"),
          function(e1,e2){
            newnum <- rational(e1@numerator * e2@numerator, e1@denominator * e2@denominator)
            return(paste(newnum@numerator,"/",newnum@denominator,sep=""))
          })

#' Rational Division
#' Will make sure the input are both in the rational class and then return the divided value of the two. Since division of rationals is just multiplication of the reciprocal of one of the rationals the value will be found by multipliying the numerator of one with denominator of the other and vice versa.
#'
#' @param e1 rational. 
#' @param e2 rational. 
#'
#' @return Divided rational of the two
setMethod("/", signature(e1 = "rational",
                         e2 = "rational"),
          function(e1,e2){
            newnum <- rational(e1@numerator * e2@denominator, e1@denominator * e2@numerator)
            return(paste(newnum@numerator,"/",newnum@denominator,sep=""))
          })
```


#part b:

Setting up class objects
```{r}
r1 <- rational(24,6)
r2 <- rational(7,230)
r3 <- rational(0,4)
```

Checking code in hw
```{r,error=TRUE}
r1
r3
r1 + r2
r1 - r2
r1 * r2
r1 / r2
r1 + r3
r1 * r3
r2 / r3
quotient(r1)
quotient(r2)
quotient(r2, digits = 3)
quotient(r2, digits = 3.14)
quotient(r2, digits = "avocado")
q2 <- quotient(r2, digits = 3)
q2
quotient(r3)
simplify(r1)
simplify(r2)
simplify(r3)
```
